In [1]:
from sklearn import datasets
bunch = datasets.load_breast_cancer()


In [2]:
data = bunch.data
labels = bunch.target  #良性惡行的結果

In [6]:
print(data)
print(type(data))
print(data.shape)

[[1.799e+01 1.038e+01 1.228e+02 ... 2.654e-01 4.601e-01 1.189e-01]
 [2.057e+01 1.777e+01 1.329e+02 ... 1.860e-01 2.750e-01 8.902e-02]
 [1.969e+01 2.125e+01 1.300e+02 ... 2.430e-01 3.613e-01 8.758e-02]
 ...
 [1.660e+01 2.808e+01 1.083e+02 ... 1.418e-01 2.218e-01 7.820e-02]
 [2.060e+01 2.933e+01 1.401e+02 ... 2.650e-01 4.087e-01 1.240e-01]
 [7.760e+00 2.454e+01 4.792e+01 ... 0.000e+00 2.871e-01 7.039e-02]]
<class 'numpy.ndarray'>
(569, 30)


In [3]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(data, labels,
                                                    test_size=0.3,
                                                    shuffle=True,
                                                    stratify=labels)

In [7]:
#Original
from sklearn.ensemble import RandomForestClassifier
randomForest = RandomForestClassifier(n_estimators=100, class_weight='balanced', n_jobs=-1, verbose=1) #分別為: 100棵樹 自動調整權重 cpu全部用上 訓練過程的資料列出來

In [10]:
# 進行訓練
randomForest.fit(X_train, Y_train)

[Parallel(n_jobs=-1)]: Using backend ThreadingBackend with 2 concurrent workers.
[Parallel(n_jobs=-1)]: Done  46 tasks      | elapsed:    0.1s
[Parallel(n_jobs=-1)]: Done 100 out of 100 | elapsed:    0.2s finished


RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight='balanced',
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=-1, oob_score=False, random_state=None, verbose=1,
                       warm_start=False)

In [11]:
# 進行預測
acc = randomForest.score(X_test, Y_test)

print('Accuracy:',acc)

Accuracy: 0.9590643274853801


[Parallel(n_jobs=2)]: Using backend ThreadingBackend with 2 concurrent workers.
[Parallel(n_jobs=2)]: Done  46 tasks      | elapsed:    0.0s
[Parallel(n_jobs=2)]: Done 100 out of 100 | elapsed:    0.0s finished


## 特徵選擇-過濾法
#### 對各個特徵進行評分(依據特徵與target的相關性、特徵的發散程度-標準差)，設定選擇的特徵個數或門檻

### 過濾方式:
* 移除變異數低的特徵
* 單變量特徵選擇

In [15]:
# 過濾方式1
#移除變異數低的特徵
from sklearn.feature_selection import VarianceThreshold
selector = VarianceThreshold(threshold=0.01) #只要特徵的變異數小於0.01，他就會被刪除
selector = selector.fit(X_train, Y_train)  #根據訓練資料和結果建立selection
X_train = selector.transform(X_train)  #透過transform刪除或留下特徵
X_test = selector.transform(X_test)
#建立模型
from sklearn.ensemble import RandomForestClassifier
randomForest = RandomForestClassifier(n_estimators=100, class_weight='balanced', n_jobs=-1, verbose=1)

In [16]:
randomForest.fit(X_train, Y_train)

[Parallel(n_jobs=-1)]: Using backend ThreadingBackend with 2 concurrent workers.
[Parallel(n_jobs=-1)]: Done  46 tasks      | elapsed:    0.1s
[Parallel(n_jobs=-1)]: Done 100 out of 100 | elapsed:    0.2s finished


RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight='balanced',
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=-1, oob_score=False, random_state=None, verbose=1,
                       warm_start=False)

In [17]:
# 進行預測
acc = randomForest.score(X_test, Y_test)
print('Accuracy:',acc)

#準確度提升

Accuracy: 0.9649122807017544


[Parallel(n_jobs=2)]: Using backend ThreadingBackend with 2 concurrent workers.
[Parallel(n_jobs=2)]: Done  46 tasks      | elapsed:    0.0s
[Parallel(n_jobs=2)]: Done 100 out of 100 | elapsed:    0.0s finished


In [19]:
# 過濾方式2
#單變量特徵選擇
from sklearn.feature_selection import SelectKBest, chi2  #SelectKBest: 只留下依據評分指標評分後前k名的特徵
selector = SelectKBest(chi2,k=10)  #留下前10個特徵比較好的(依據chi2評分標準)去建構selector
selector = selector.fit(X_train, Y_train)
X_train = selector.transform(X_train)
X_test = selector.transform(X_test)
#建立模型
from sklearn.ensemble import RandomForestClassifier
randomForest = RandomForestClassifier(n_estimators=120, criterion='entropy', class_weight='balanced', n_jobs=-1, verbose=1)

In [20]:
randomForest.fit(X_train, Y_train)

[Parallel(n_jobs=-1)]: Using backend ThreadingBackend with 2 concurrent workers.
[Parallel(n_jobs=-1)]: Done  46 tasks      | elapsed:    0.1s
[Parallel(n_jobs=-1)]: Done 120 out of 120 | elapsed:    0.2s finished


RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight='balanced',
                       criterion='entropy', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=120,
                       n_jobs=-1, oob_score=False, random_state=None, verbose=1,
                       warm_start=False)

In [21]:
# 進行預測
acc = randomForest.score(X_test, Y_test)
print('Accuracy:',acc)

#準確度提升

Accuracy: 0.9766081871345029


[Parallel(n_jobs=2)]: Using backend ThreadingBackend with 2 concurrent workers.
[Parallel(n_jobs=2)]: Done  46 tasks      | elapsed:    0.0s
[Parallel(n_jobs=2)]: Done 120 out of 120 | elapsed:    0.0s finished
